# Introduction to Deep Learning  
## Building a Neural Network from Scratch

In this notebook, we will develop a foundational understanding of neural networks by constructing one from first principles.

We will NOT begin with complex libraries or mathematical derivations. Instead, we will focus on the core computational idea behind deep learning.

By the end of this notebook, you will understand:

• What a neuron is  
• How neurons combine to form networks  
• What forward propagation means  
• How modern frameworks like PyTorch implement these ideas  

# What is an Artificial Neuron?

An artificial neuron is a simple mathematical function that performs three steps:

### Step 1 — Multiply inputs by weights  
Each input is assigned an importance value called a **weight**.

### Step 2 — Add the weighted inputs  
The neuron computes a weighted sum.

### Step 3 — Add a bias  
The bias allows the neuron to shift its output.

### Mathematical Form:

output = (input₁ × weight₁) + (input₂ × weight₂) + bias

This computation is known as **forward propagation**.


In [21]:
# Creating Our First Artificial Neuron

# Let us assume we want to predict whether a student will pass an exam
# based on two inputs:
# 1. Number of hours studied
# 2. Number of hours slept


# Input variables
study_hours = 4
sleep_hours = 6

# Weight variables
# These represent how important each input is
weight_study = 0.8
weight_sleep = 0.2

# Bias variable
# This represents the neuron's tendency to output higher or lower values
bias = -3


# Forward propagation:
# Multiply each input by its weight and add the bias
output = (study_hours * weight_study) + (sleep_hours * weight_sleep) + bias


# Display the result
print("Neuron output:", output)


Neuron output: 1.4000000000000004


## Experiment

Modify the following variables and rerun the cell:

• Increase `weight_study`  
• Decrease `weight_sleep`  
• Change the bias  

Observe how the output changes.

Reflect on the following:

- Which variable appears more important for predicting success?
- What happens if the bias becomes very large?
- Can you force the neuron to always produce a positive output?


# Activation Functions

Currently, the neuron outputs a raw numerical value.

However, neural networks typically pass this value through an **activation function**.

An activation function introduces **non-linearity**, allowing networks to learn complex patterns.

We will use one of the simplest and most widely used activation functions:

## ReLU (Rectified Linear Unit)

ReLU(x) = max(0, x)

If the input is negative, the function returns 0.  
Otherwise, it returns the input unchanged.


In [22]:
# Defining the ReLU activation function

def relu(x):
    # max(0, x) returns the greater value between 0 and x
    return max(0, x)


# Apply activation to the neuron output
activated_output = relu(output)

print("Output after ReLU:", activated_output)


Output after ReLU: 1.4000000000000004


## Experiment

Set the bias to a very negative number such as:

bias = -10

Run the neuron again.

Notice that the output becomes 0 after activation.

This situation is sometimes informally described as a neuron becoming inactive.


# Building a Small Neural Network

A single neuron is limited in what it can represent.

Neural networks gain their power by combining many neurons into **layers**.

We will now construct a small network with:

• 2 input features  
• 1 hidden layer containing 3 neurons  
• 1 output neuron  

This structure is called a **fully connected neural network** because every neuron receives all inputs from the previous layer.


In [23]:
# Hidden Layer Computation

study = 4
sleep = 6


# Neuron 1
n1 = (study * 0.5) + (sleep * 0.5) - 2

# Neuron 2
n2 = (study * 1.0) + (sleep * -0.2) - 3

# Neuron 3
n3 = (study * -0.3) + (sleep * 0.9) - 2


print("Hidden layer outputs (before activation):")
print(n1, n2, n3)


Hidden layer outputs (before activation):
3.0 -0.20000000000000018 2.2


In [24]:
# Applying ReLU to the hidden layer

n1 = relu(n1)
n2 = relu(n2)
n3 = relu(n3)

print("Hidden layer outputs (after activation):")
print(n1, n2, n3)


Hidden layer outputs (after activation):
3.0 0 2.2


Each neuron can learn a different pattern.

For example:

• One neuron may emphasize studying  
• Another may emphasize sleep  
• Another may detect imbalance  

The network combines these intermediate signals to form a final decision.


In [25]:
# Output Layer

final_output = (n1 * 0.6) + (n2 * 0.3) + (n3 * 0.8) - 1

print("Final network score:", final_output)


# Convert the numerical output into a decision
if final_output > 0:
    print("Prediction: PASS")
else:
    print("Prediction: FAIL")


Final network score: 2.56
Prediction: PASS


## Exploration

Adjust the weights in the hidden or output layer and observe how the prediction changes.

Consider the following challenges:

• Can you make the network always predict PASS?  
• Can you make sleep more influential than studying?  
• Can you force the network to always predict FAIL?


# Implementing the Same Idea Using PyTorch

Modern deep learning libraries automate these computations.

We will now use **PyTorch**, one of the most widely used deep learning frameworks.


In [26]:
# Import PyTorch
import torch

# Import the neural network module
import torch.nn as nn


In [27]:
# Creating a Linear Layer

# nn.Linear(input_features, output_features)

layer = nn.Linear(2, 3)

print("Weights:")
print(layer.weight)

print("\nBias:")
print(layer.bias)


Weights:
Parameter containing:
tensor([[ 0.4620,  0.0735],
        [-0.2121, -0.6142],
        [ 0.6514,  0.3762]], requires_grad=True)

Bias:
Parameter containing:
tensor([ 0.6573, -0.0890,  0.4851], requires_grad=True)


Observe that PyTorch automatically creates:

• A weight matrix  
• A bias vector  

These are the same quantities we manually defined earlier.


In [28]:
# Passing data through the layer

inputs = torch.tensor([4.0, 6.0])

output = layer(inputs)

print("Layer output:")
print(output)


Layer output:
tensor([ 2.9462, -4.6226,  5.3479], grad_fn=<ViewBackward0>)


# Task 1 - Build a Neural Network Using PyTorch

You will now construct a small neural network.

## Architecture Requirements:

Input layer → 2 features  
Hidden layer → 4 neurons  
Output layer → 1 neuron  

Both layers must be fully connected.

Use ReLU activation after the hidden layer.

---

## Your Objectives:

1. Create the hidden layer  
2. Create the output layer  
3. Pass data forward through the network  
4. Print the final output  

Complete the code below.


In [29]:
import torch
import torch.nn as nn


# Create a sample input tensor
inputs = torch.tensor([5.0, 3.0])


# TODO:
# Create a hidden layer with 2 input features and 4 output features
hidden_layer = nn.Linear(2, 4)


# TODO:
# Create an output layer with 4 input features and 1 output feature
output_layer = nn.Linear(4, 1)


# Forward propagation

# Pass inputs through hidden layer
hidden_output = hidden_layer(inputs)

# Apply ReLU activation
hidden_output = torch.relu(hidden_output)

# Pass through output layer
final_output = output_layer(hidden_output)


print("Network output:")
print(final_output)


Network output:
tensor([0.7066], grad_fn=<ViewBackward0>)


# Key Takeaways

• Neural networks are compositions of simple mathematical operations.  
• Forward propagation is simply weighted addition followed by activation.  
• Deep learning frameworks automate these computations efficiently.

You now understand the core computational idea behind modern AI systems.


# Task 2

So far, our neural network produces an output.

But how do we know if the prediction is good or bad?

We need a way to **measure error**.

This is the role of a **loss function**.

A loss function tells us how far the network's prediction is from the correct answer.

Lower loss = better predictions.

## Mean Squared Error (MSE)

One of the simplest loss functions is **Mean Squared Error**.

Steps:

1. Compute the difference between prediction and true value  
2. Square the difference  
3. Take the average  

### Formula:

MSE = average((prediction − true value)²)

Why square the error?

• Prevents negative values from cancelling positives  
• Penalizes large mistakes more heavily


## Your Task

You are given a neural network and some sample students.

Each student has:

[study hours, sleep hours]

The label represents:

1 → Pass  
0 → Fail  

Your objectives:

1. Pass the data through the network  
2. Compute the loss using Mean Squared Error  
3. Print the loss  

Observe what the loss value tells you about the network.


In [30]:
import torch
import torch.nn as nn
import numpy as np

# Define the network
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)


# Sample dataset
students = torch.tensor([
    [5.0, 7.0],
    [2.0, 3.0],
    [6.0, 2.0],
    [1.0, 1.0]
])

labels = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0]
])

# TODO: Generate predictions
predictions = model(students)
probs = torch.sigmoid(predictions)


# TODO: Create the loss function
loss_fn = lambda probs : torch.mean((labels-probs)**2)

# print(*probs) 
# TODO: Compute the loss
loss = loss_fn(probs)

# print(predictions)
print("Loss:", loss.item())

Loss: 0.2200523316860199
